replicaCount: 1

image:
  repository: linuxserver/heimdall
  tag: "2.5.7"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "25m"
    memory: "64Mi"
  limits:
    cpu: "100m"
    memory: "128Mi"

storage:
  config: 1Gi

service:
  port: 80

config:
  puid: 1000
  pgid: 1000
  timezone: "Europe/Budapest"

global:
  storageClass: ""

nodeSelector: {}
tolerations: []
affinity: {}
