apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ignition.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels: {{- include "ignition.labels" . | nindent 4 }}
type: Opaque
stringData:
  IGNITION_ADMIN_USERNAME: {{ .Values.auth.adminUsername | quote }}
  IGNITION_ADMIN_PASSWORD: {{ .Values.auth.adminPassword | quote }}
