apiVersion: v1
kind: Service
metadata:
  name: {{ include "ignition.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "ignition.labels" . | nindent 4 }}
spec:
  selector: {{- include "ignition.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.gateway.port }}
      targetPort: {{ .Values.service.gateway.port }}
      name: http
    - port: {{ .Values.service.gateway_ssl.port }}
      targetPort: {{ .Values.service.gateway_ssl.port }}
      name: https
