#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════════════════════
#  FDE Platform Installer v3  ·  Accenture Factory Digital Edge
#  Interactive TUI wizard + fully autonomous K8s stack deployment
#
#  TUI mode (default):   sudo ./install.sh
#  CLI / CI mode:        sudo ./install.sh --ip 192.168.1.10 [OPTIONS]
#  Help:                 ./install.sh --help
# ══════════════════════════════════════════════════════════════════════════════
set -euo pipefail

INSTALLER_VERSION="3.0"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG=/tmp/fde-install.log

# ── Colour palette ────────────────────────────────────────────────────────────
P=$'\e[38;5;129m'; L=$'\e[38;5;183m'; W=$'\e[1;97m'; G=$'\e[38;5;82m'
Y=$'\e[38;5;220m'; R=$'\e[38;5;196m'; D=$'\e[38;5;244m'; N=$'\e[0m'

# ── Banner ────────────────────────────────────────────────────────────────────
show_banner() {
  clear
  # Top arm: P (purple). Bottom arm: L (lavender), exact mirror of top.
  printf '%s' "${P}"
  printf '%s\n' \
    ' *#' \
    ' #****##' \
    ' #*********#' \
    ' #************#**' \
    ' #******************#' \
    '     #*****************#*#' \
    '         *#*****************##' \
    '              #******************#' \
    '                  #****************#' \
    '                      ###**********#'
  # TIP — P→L colour transition mid-line
  printf '%s%s\n' '                       #%%' "${L}##*******##"
  # Bottom arm: exact mirror of top arm (lines 10→1), in L colour
  printf '%s\n' \
    '                      ###**********#' \
    '                  #****************#' \
    '              #******************#' \
    '         *#*****************##' \
    '     #*****************#*#' \
    ' #******************#' \
    ' #************#**' \
    ' #*********#' \
    ' #****##' \
    ' *#'
  printf '%s\n' "${N}"
  printf "        ${W}Factory Digital Edge${N}  ${D}·${N}  ${P}Accenture${N}\n"
  printf "        ${D}Full K8s Stack Installer  v%s${N}\n" "$INSTALLER_VERSION"
  printf "        ${D}─────────────────────────────────────────${N}\n\n"
}

# ── Logging ───────────────────────────────────────────────────────────────────
STEP=0; PHASE_NUM=0
phase()  { PHASE_NUM=$((PHASE_NUM+1)); printf "\n${P}━━━ PHASE %d: %s ${N}\n" "$PHASE_NUM" "$1"; }
step()   { STEP=$((STEP+1)); printf "  ${W}[%d]${N} %s\n" "$STEP" "$1"; }
ok()     { printf "      ${G}✔${N}  %s\n" "$1"; }
warn()   { printf "      ${Y}⚠${N}  %s\n" "$1"; }
err()    { printf "      ${R}✘${N}  %s\n" "$1" >&2; exit 1; }
info()   { printf "      ${D}→${N}  %s\n" "$1"; }
skip()   { printf "      ${D}↷${N}  %s\n" "$1 (already deployed — skipping)"; }

_spin_pid=""
_spin_start() {
  printf "      ${D}⟳${N}  %s..." "$1"
  ( while true; do
      for c in '⠋' '⠙' '⠹' '⠸' '⠼' '⠴' '⠦' '⠧' '⠇' '⠏'; do
        printf "\r      ${P}%s${N}  %s..." "$c" "$1"; sleep 0.08
      done
    done ) &
  _spin_pid=$!; disown "$_spin_pid" 2>/dev/null || true
}
_spin_stop() {
  [[ -n "${_spin_pid:-}" ]] && kill "$_spin_pid" 2>/dev/null || true; _spin_pid=""
  printf "\r      ${G}✔${N}  %-60s\n" "$1"
}
_spin_fail() {
  [[ -n "${_spin_pid:-}" ]] && kill "$_spin_pid" 2>/dev/null || true; _spin_pid=""
  printf "\r      ${R}✘${N}  FAILED — see %s\n" "$LOG"
  tail -20 "$LOG"; exit 1
}
run() {
  local msg="$1"; shift
  _spin_start "$msg"
  if "$@" >>"$LOG" 2>&1; then _spin_stop "$msg"; else _spin_fail; fi
}

# ── Defaults ──────────────────────────────────────────────────────────────────
DEPLOY_MODE="single"
NODE_IP="${FDE_IP:-}"; NODE_HOSTNAME="${FDE_HOSTNAME:-fde-essen}"
DOMAIN="${FDE_DOMAIN:-fde-essen.local}"; SITE="${FDE_SITE:-essen}"
VLLM_URL="${FDE_VLLM_URL:-}"; OBS_URL="${FDE_OBS_URL:-}"; OBS_KEY="${FDE_OBS_KEY:-}"
JOIN_URL="${FDE_JOIN_URL:-}"; JOIN_TOKEN="${FDE_JOIN_TOKEN:-}"; WORKER_TIER="worker"
DRY_RUN=false; CLI_MODE=false
NS=uns; CHARTS_DIR="${SCRIPT_DIR}/charts"
MCP_YAML="${SCRIPT_DIR}/mcp-servers-deployment.yaml"
IGN_MODULES_DIR="${HOME}/ignition-modules"

PW_CLICKHOUSE="${FDE_PW_CLICKHOUSE:-fde-clickhouse-secret}"
PW_NEO4J="${FDE_PW_NEO4J:-fde-neo4j-secret}"
PW_IGNITION="${FDE_PW_IGNITION:-admin}"
PW_GRAFANA="${FDE_PW_GRAFANA:-fde-grafana-secret}"
PW_PGADMIN="${FDE_PW_PGADMIN:-admin}"
PW_EMQX="${FDE_PW_EMQX:-fde-emqx-secret}"
# ── .env file — auto-source if present (generated by installer on first run) ──
FDE_ENV_FILE="${SCRIPT_DIR}/.env"
[[ -f "${FDE_ENV_FILE}" ]] && {
  # shellcheck source=/dev/null
  source "${FDE_ENV_FILE}"
  PW_CLICKHOUSE="${FDE_PW_CLICKHOUSE:-${PW_CLICKHOUSE}}"
  PW_NEO4J="${FDE_PW_NEO4J:-${PW_NEO4J}}"
  PW_IGNITION="${FDE_PW_IGNITION:-${PW_IGNITION}}"
  PW_GRAFANA="${FDE_PW_GRAFANA:-${PW_GRAFANA}}"
  PW_PGADMIN="${FDE_PW_PGADMIN:-${PW_PGADMIN}}"
  PW_EMQX="${FDE_PW_EMQX:-${PW_EMQX}}"
  NODE_IP="${FDE_NODE_IP:-${NODE_IP:-}}"
  DOMAIN="${FDE_DOMAIN:-${DOMAIN:-}}"
  VLLM_URL="${FDE_VLLM_URL:-${VLLM_URL:-}}"
}

SVC_EMQX=true; SVC_CLICKHOUSE=true; SVC_NEO4J=true; SVC_QDRANT=true
SVC_IGNITION=true; SVC_PREDMAINT=true; SVC_MONITORING=true; SVC_LOKI=true
SVC_PGADMIN=true; SVC_MAESTROHUB=false; SVC_LITMUSEDGE=false; SVC_OBSIDIAN=false

# ── CLI args ──────────────────────────────────────────────────────────────────
usage() {
cat <<EOF
${W}FDE Platform Installer v${INSTALLER_VERSION}${N}  —  ${P}Accenture Factory Digital Edge${N}

${W}Usage:${N}
  sudo ./install.sh                    Interactive TUI (recommended)
  sudo ./install.sh --ip <IP> [OPTS]   CLI / CI mode

${W}Options:${N}
  --ip <addr>          Node IP (triggers CLI mode)
  --hostname <h>       K8s node hostname           (default: fde-essen)
  --domain <d>         Ingress base domain          (default: fde-essen.local)
  --site <s>           Short site name              (default: essen)
  --mode <m>           single|control-plane|worker  (default: single)
  --join-url <url>     k3s API URL (worker mode)
  --join-token <tok>   k3s node token (worker mode)
  --worker-tier <t>    stateful|worker|ot-edge      (default: worker)
  --vllm-url <url>     External vLLM endpoint
  --obs-url <url>      Obsidian REST API URL
  --obs-key <key>      Obsidian REST API key
  --pw-clickhouse <p>  ClickHouse password
  --pw-neo4j <p>       Neo4j password
  --pw-ignition <p>    Ignition admin password
  --pw-grafana <p>     Grafana admin password
  --pw-pgadmin <p>     pgAdmin password
  --skip <list>        Comma-separated services to skip
  --dry-run            Print actions, make no changes
  --no-tui             Force non-interactive CLI mode
  --help               Show this help

${W}Environment overrides:${N}
  FDE_IP, FDE_HOSTNAME, FDE_DOMAIN, FDE_SITE, FDE_VLLM_URL,
  FDE_OBS_URL, FDE_OBS_KEY,
  FDE_PW_CLICKHOUSE, FDE_PW_NEO4J, FDE_PW_IGNITION, FDE_PW_GRAFANA, FDE_PW_PGADMIN
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --ip)             NODE_IP="$2";       CLI_MODE=true; shift 2 ;;
    --hostname)       NODE_HOSTNAME="$2"; shift 2 ;;
    --domain)         DOMAIN="$2";        shift 2 ;;
    --site)           SITE="$2";          shift 2 ;;
    --mode)           DEPLOY_MODE="$2";   shift 2 ;;
    --join-url)       JOIN_URL="$2";      shift 2 ;;
    --join-token)     JOIN_TOKEN="$2";    shift 2 ;;
    --worker-tier)    WORKER_TIER="$2";   shift 2 ;;
    --vllm-url)       VLLM_URL="$2";      shift 2 ;;
    --obs-url)        OBS_URL="$2";       shift 2 ;;
    --obs-key)        OBS_KEY="$2";       shift 2 ;;
    --pw-clickhouse)  PW_CLICKHOUSE="$2"; shift 2 ;;
    --pw-neo4j)       PW_NEO4J="$2";      shift 2 ;;
    --pw-ignition)    PW_IGNITION="$2";   shift 2 ;;
    --pw-grafana)     PW_GRAFANA="$2";    shift 2 ;;
    --pw-pgadmin)     PW_PGADMIN="$2";    shift 2 ;;
    --skip)
      IFS=',' read -ra _SKIPS <<< "$2"; shift 2
      for s in "${_SKIPS[@]}"; do
        case "$s" in
          emqx)       SVC_EMQX=false ;;       clickhouse) SVC_CLICKHOUSE=false ;;
          neo4j)     SVC_NEO4J=false ;;       qdrant)     SVC_QDRANT=false ;;
          ignition)   SVC_IGNITION=false ;;   predmaint)  SVC_PREDMAINT=false ;;
          monitoring) SVC_MONITORING=false ;; loki)       SVC_LOKI=false ;;
          pgadmin)    SVC_PGADMIN=false ;;    maestrohub) SVC_MAESTROHUB=false ;;
          litmusedge) SVC_LITMUSEDGE=false ;; obsidian)   SVC_OBSIDIAN=false ;;
        esac
      done ;;
    --dry-run)  DRY_RUN=true;   shift ;;
    --no-tui)   CLI_MODE=true;  shift ;;
    --help|-h)  show_banner; usage; exit 0 ;;
    *)          printf "Unknown option: %s\n" "$1" >&2; usage; exit 1 ;;
  esac
done

maybe() { $DRY_RUN && printf "      ${D}[dry-run]${N} %s\n" "$*" || "$@"; }

# ══════════════════════════════════════════════════════════════════════════════
#  TUI WIZARD  (whiptail)
# ══════════════════════════════════════════════════════════════════════════════

WT_BT="  FDE Platform Installer v${INSTALLER_VERSION}  ·  Accenture Factory Digital Edge  "

auto_detect_ip() {
  ip route get 1.1.1.1 2>/dev/null | awk '/src/{print $7}' | head -1 \
    || hostname -I 2>/dev/null | awk '{print $1}' \
    || echo "0.0.0.0"
}

wt_welcome() {
  whiptail --backtitle "$WT_BT" --title " Welcome " --msgbox \
"FDE Platform Installer  v${INSTALLER_VERSION}

This wizard configures and autonomously deploys the full
Factory Digital Edge stack on this machine.

  • Idempotent — safe to re-run on existing nodes
  • All components deployed via Helm + kubectl
  • Supports single-node, control-plane, or worker join

Requirements:
  • Ubuntu 22.04 / 24.04 / 26.04  (x86_64 or ARM64)
  • Run as root (sudo ./install.sh)
  • Internet access for package downloads

Press  Enter  to begin." 18 62
}

wt_mode() {
  DEPLOY_MODE=$(whiptail --backtitle "$WT_BT" --title " Deployment Mode " --nocancel \
    --menu "\nHow will this node be used?" 15 68 3 \
    "single"          "Full stack on this machine  (recommended)" \
    "control-plane"   "k3s master + stack; print worker join token" \
    "worker"          "Join an existing FDE cluster (k3s agent only)" \
    3>&1 1>&2 2>&3)
}

wt_network() {
  local detected; detected="$(auto_detect_ip)"
  local out
  out=$(whiptail --backtitle "$WT_BT" --title " Network Configuration " --nocancel \
    --form "\nConfigure this node's network identity:" 17 68 6 \
    "Node IP address  :" 1 1 "${NODE_IP:-$detected}" 1 21 38 64 \
    "Hostname         :" 2 1 "$NODE_HOSTNAME"         2 21 28 64 \
    "Ingress domain   :" 3 1 "$DOMAIN"               3 21 38 64 \
    "Site tag (short) :" 4 1 "$SITE"                 4 21 18 32 \
    "vLLM URL  (opt.) :" 5 1 "$VLLM_URL"             5 21 38 128 \
    "Obsidian URL(opt):" 6 1 "$OBS_URL"              6 21 38 128 \
    3>&1 1>&2 2>&3) || return 0
  mapfile -t _f <<< "$out"
  NODE_IP="${_f[0]}"; NODE_HOSTNAME="${_f[1]}"; DOMAIN="${_f[2]}"
  SITE="${_f[3]}"; VLLM_URL="${_f[4]}"; OBS_URL="${_f[5]}"
  [[ -z "$NODE_IP" ]] && { whiptail --backtitle "$WT_BT" --msgbox "Node IP cannot be empty." 8 40; wt_network; }
}

wt_worker() {
  local out
  out=$(whiptail --backtitle "$WT_BT" --title " Worker Join Config " --nocancel \
    --form "\nEnter the control-plane details:" 13 68 3 \
    "Control-plane URL:" 1 1 "${JOIN_URL:-https://192.168.100.102:6443}" 1 21 38 128 \
    "Join token       :" 2 1 "$JOIN_TOKEN"   2 21 42 256 \
    "Worker tier      :" 3 1 "$WORKER_TIER"  3 21 16 32 \
    3>&1 1>&2 2>&3) || return 0
  mapfile -t _f <<< "$out"
  JOIN_URL="${_f[0]}"; JOIN_TOKEN="${_f[1]}"; WORKER_TIER="${_f[2]}"
}

wt_services() {
  local sel
  sel=$(whiptail --backtitle "$WT_BT" --title " Services to Deploy " --nocancel \
    --checklist "\nSPACE to toggle, arrows to navigate, Enter to confirm:" 22 72 12 \
    "emqx"        "EMQX 5.8 — MQTT broker + SparkplugB backbone"        ON  \
    "clickhouse"  "ClickHouse — time-series historian"                  ON  \
    "neo4j"       "Neo4j — graph database (UNS topology + knowledge base)" ON  \
    "qdrant"      "Qdrant — vector database (RAG / embeddings)"         ON  \
    "ignition"    "Ignition SCADA — OT/SCADA platform"                 ON  \
    "predmaint"   "predmaint — ML predictive maintenance inference"     ON  \
    "monitoring"  "Prometheus + Grafana + AlertManager"                 ON  \
    "loki"        "Loki + Promtail — log aggregation"                   ON  \
    "pgadmin"     "pgAdmin — PostgreSQL web UI"                         ON  \
    "maestrohub"  "MaestroHub (n8n) — workflow automation"             OFF \
    "litmusedge"  "LitmusEdge — OT gateway (needs OT hardware)"        OFF \
    "obsidian"    "Obsidian viewer — read-only vault web UI"            OFF \
    3>&1 1>&2 2>&3)

  SVC_EMQX=false; SVC_CLICKHOUSE=false; SVC_NEO4J=false; SVC_QDRANT=false
  SVC_IGNITION=false; SVC_PREDMAINT=false; SVC_MONITORING=false; SVC_LOKI=false
  SVC_PGADMIN=false; SVC_MAESTROHUB=false; SVC_LITMUSEDGE=false; SVC_OBSIDIAN=false
  for s in $sel; do
    s="${s//\"/}"
    case "$s" in
      emqx)       SVC_EMQX=true ;;       clickhouse) SVC_CLICKHOUSE=true ;;
      neo4j)     SVC_NEO4J=true ;;       qdrant)     SVC_QDRANT=true ;;
      ignition)   SVC_IGNITION=true ;;   predmaint)  SVC_PREDMAINT=true ;;
      monitoring) SVC_MONITORING=true ;; loki)       SVC_LOKI=true ;;
      pgadmin)    SVC_PGADMIN=true ;;    maestrohub) SVC_MAESTROHUB=true ;;
      litmusedge) SVC_LITMUSEDGE=true ;; obsidian)   SVC_OBSIDIAN=true ;;
    esac
  done

  if $SVC_OBSIDIAN && [[ -z "$OBS_URL" ]]; then
    OBS_URL=$(whiptail --backtitle "$WT_BT" --title " Obsidian API " --nocancel \
      --inputbox "Obsidian REST API URL:" 8 60 "http://192.168.100.207:27123" 3>&1 1>&2 2>&3)
    OBS_KEY=$(whiptail --backtitle "$WT_BT" --title " Obsidian API Key " --nocancel \
      --passwordbox "Obsidian REST API key:" 8 60 3>&1 1>&2 2>&3)
  fi
}

wt_passwords() {
  local choice
  choice=$(whiptail --backtitle "$WT_BT" --title " Passwords " --nocancel \
    --menu "\nService passwords:" 12 62 2 \
    "defaults"  "Use built-in defaults (demo / dev use)" \
    "custom"    "Enter custom passwords for each service" \
    3>&1 1>&2 2>&3)
  [[ "$choice" != "custom" ]] && return 0

  local out
  out=$(whiptail --backtitle "$WT_BT" --title " Custom Passwords " --nocancel \
    --form "\nLeave blank to keep current value:" 14 66 5 \
    "ClickHouse     :" 1 1 "$PW_CLICKHOUSE" 1 19 38 64 \
    "Neo4j          :" 2 1 "$PW_NEO4J"      2 19 38 64 \
    "Ignition admin :" 3 1 "$PW_IGNITION"   3 19 38 64 \
    "Grafana admin  :" 4 1 "$PW_GRAFANA"    4 19 38 64 \
    "pgAdmin        :" 5 1 "$PW_PGADMIN"    5 19 38 64 \
    3>&1 1>&2 2>&3) || return 0
  mapfile -t _p <<< "$out"
  [[ -n "${_p[0]:-}" ]] && PW_CLICKHOUSE="${_p[0]}"
  [[ -n "${_p[1]:-}" ]] && PW_NEO4J="${_p[1]}"
  [[ -n "${_p[2]:-}" ]] && PW_IGNITION="${_p[2]}"
  [[ -n "${_p[3]:-}" ]] && PW_GRAFANA="${_p[3]}"
  [[ -n "${_p[4]:-}" ]] && PW_PGADMIN="${_p[4]}"
}

wt_confirm() {
  local svc_list=""
  $SVC_EMQX        && svc_list+="  ✔ EMQX 5.8 (MQTT broker)\n"
  $SVC_CLICKHOUSE  && svc_list+="  ✔ ClickHouse\n"
  $SVC_NEO4J       && svc_list+="  ✔ Neo4j (graph DB)\n"
  $SVC_QDRANT      && svc_list+="  ✔ Qdrant (vector DB)\n"
  $SVC_IGNITION    && svc_list+="  ✔ Ignition SCADA\n"
  $SVC_PREDMAINT   && svc_list+="  ✔ predmaint (ML inference)\n"
  $SVC_MONITORING  && svc_list+="  ✔ Prometheus + Grafana\n"
  $SVC_LOKI        && svc_list+="  ✔ Loki + Promtail\n"
  $SVC_PGADMIN     && svc_list+="  ✔ pgAdmin\n"
  $SVC_MAESTROHUB  && svc_list+="  ✔ MaestroHub (n8n)\n"
  $SVC_LITMUSEDGE  && svc_list+="  ✔ LitmusEdge\n"
  $SVC_OBSIDIAN    && svc_list+="  ✔ Obsidian viewer\n"

  local msg
  printf -v msg \
"Deployment Summary
──────────────────
Mode      : %s
Node IP   : %s
Hostname  : %s
Domain    : %s
Site      : %s
%s
Services:
%s
Proceed with deployment?" \
    "$DEPLOY_MODE" "$NODE_IP" "$NODE_HOSTNAME" "$DOMAIN" "$SITE" \
    "${VLLM_URL:+vLLM URL  : $VLLM_URL}" \
    "$svc_list"

  whiptail --backtitle "$WT_BT" --title " Confirm " \
    --yesno "$msg" 28 62 || {
    whiptail --backtitle "$WT_BT" --msgbox "Cancelled. No changes were made." 8 44
    exit 0
  }
}

run_tui_wizard() {
  wt_welcome
  wt_mode
  if [[ "$DEPLOY_MODE" == "worker" ]]; then
    wt_network   # still need IP for output
    wt_worker
    wt_confirm
  else
    wt_network
    wt_services
    wt_passwords
    wt_confirm
  fi
}

# ══════════════════════════════════════════════════════════════════════════════
#  ENTRY POINT
# ══════════════════════════════════════════════════════════════════════════════
show_banner
: > "$LOG"

if ! $CLI_MODE && [[ -t 0 && -t 1 ]]; then
  if ! command -v whiptail &>/dev/null; then
    printf "  ${Y}⚠${N}  whiptail not found — installing it first...\n"
    apt-get install -y -qq whiptail 2>/dev/null || true
  fi
  if command -v whiptail &>/dev/null; then
    run_tui_wizard
  else
    warn "Could not install whiptail. Falling back to CLI mode."
    [[ -z "$NODE_IP" ]] && err "--ip is required.  Usage: sudo ./install.sh --ip <IP>"
  fi
else
  [[ -z "$NODE_IP" && "$DEPLOY_MODE" != "worker" ]] && \
    err "--ip is required in CLI mode.  Usage: sudo ./install.sh --ip <IP>"
fi

# ── Print resolved configuration ──────────────────────────────────────────────
printf "  ${D}Mode      :${N} ${W}%s${N}\n"  "$DEPLOY_MODE"
printf "  ${D}Node IP   :${N} ${W}%s${N}\n"  "$NODE_IP"
printf "  ${D}Hostname  :${N} ${W}%s${N}\n"  "$NODE_HOSTNAME"
printf "  ${D}Domain    :${N} ${W}%s${N}\n"  "$DOMAIN"
printf "  ${D}Namespace :${N} ${W}%s${N}\n"  "$NS"
printf "  ${D}Log       :${N} ${W}%s${N}\n"  "$LOG"
$DRY_RUN && printf "\n  ${Y}⚠  DRY-RUN mode — no changes will be made${N}\n"
printf "\n"
[[ $EUID -ne 0 ]] && err "Must run as root:  sudo ./install.sh"

# ══════════════════════════════════════════════════════════════════════════════
#  WORKER-ONLY PATH
# ══════════════════════════════════════════════════════════════════════════════
if [[ "$DEPLOY_MODE" == "worker" ]]; then
  phase "System prerequisites"
  run "apt update" apt-get update -qq
  run "Install curl" apt-get install -y -qq curl

  phase "Join cluster"
  [[ -z "$JOIN_URL"   ]] && err "--join-url required for worker mode"
  [[ -z "$JOIN_TOKEN" ]] && err "--join-token required for worker mode"
  if command -v k3s &>/dev/null; then
    skip "k3s already installed"
  else
    _spin_start "Joining cluster at ${JOIN_URL} (tier=${WORKER_TIER})"
    maybe curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent \
      --server ${JOIN_URL} --token ${JOIN_TOKEN} \
      --node-label uns.fde/tier=${WORKER_TIER}" sh - >>"$LOG" 2>&1
    _spin_stop "k3s agent joined"
  fi
  printf "\n${P}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}\n"
  printf "${W} Worker joined!  Tier: %s${N}\n" "$WORKER_TIER"
  printf "${P}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}\n\n"
  printf "  Verify on control-plane:  ${W}kubectl get nodes -L uns.fde/tier${N}\n\n"
  exit 0
fi

# ══════════════════════════════════════════════════════════════════════════════
#  PHASE 1 — System prerequisites
# ══════════════════════════════════════════════════════════════════════════════
phase "System prerequisites"

step "Set hostname to ${NODE_HOSTNAME}"
if [[ "$(hostname)" != "${NODE_HOSTNAME}" ]]; then
  maybe hostnamectl set-hostname "${NODE_HOSTNAME}"
  ok "Hostname → ${NODE_HOSTNAME}"
else skip "Hostname already ${NODE_HOSTNAME}"; fi

step "Install OS packages"
run "apt update" apt-get update -qq
run "Install deps" apt-get install -y -qq \
  curl git jq ca-certificates gnupg lsb-release \
  apt-transport-https software-properties-common

# ══════════════════════════════════════════════════════════════════════════════
#  PHASE 2 — k3s control-plane
# ══════════════════════════════════════════════════════════════════════════════
phase "k3s control-plane"

step "Install k3s"
if command -v k3s &>/dev/null && kubectl get nodes &>/dev/null 2>&1; then
  # Ensure traefik is disabled in config even on pre-existing k3s installs
  mkdir -p /etc/rancher/k3s
  if ! grep -q 'disable.*traefik' /etc/rancher/k3s/config.yaml 2>/dev/null; then
    printf '\ndisable:\n  - traefik\n' >> /etc/rancher/k3s/config.yaml
  fi
  skip "k3s already running"
else
  _spin_start "Installing k3s"
  maybe curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="\
    server --cluster-init --tls-san ${NODE_IP} \
    --disable traefik --flannel-backend=none --disable-network-policy \
    --node-label uns.fde/tier=stateful --write-kubeconfig-mode 644" sh - >>"$LOG" 2>&1
  _spin_stop "k3s installed"
fi

step "Wait for API server"
_spin_start "k3s API"
for i in $(seq 1 30); do kubectl get nodes &>/dev/null 2>&1 && break || sleep 3; done
kubectl get nodes &>/dev/null || err "k3s API not responding after 90s"
_spin_stop "API server ready"

step "Configure kubeconfig"
mkdir -p "${HOME}/.kube"
maybe cp /etc/rancher/k3s/k3s.yaml "${HOME}/.kube/config"
maybe chmod 600 "${HOME}/.kube/config"
ok "kubeconfig → ${HOME}/.kube/config"

step "Label control-plane node"
NODE_NAME=$(kubectl get nodes -o jsonpath='{.items[0].metadata.name}')
maybe kubectl label node "${NODE_NAME}" uns.fde/tier=stateful --overwrite >>"$LOG" 2>&1
ok "Labelled ${NODE_NAME}"

step "Install Helm"
if command -v helm &>/dev/null; then
  skip "Helm $(helm version --short 2>/dev/null) already installed"
else
  run "Installing Helm" bash <(curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3)
fi

[[ "$DEPLOY_MODE" == "control-plane" ]] && {
  TOKEN=$(cat /var/lib/rancher/k3s/server/node-token 2>/dev/null || echo "unavailable")
  printf "\n  ${Y}Worker join token:${N}\n  ${W}%s${N}\n" "$TOKEN"
  printf "  ${Y}Join URL:${N} ${W}https://%s:6443${N}\n" "$NODE_IP"
}

# ══════════════════════════════════════════════════════════════════════════════
#  PHASE 3 — Calico CNI
# ══════════════════════════════════════════════════════════════════════════════
phase "Calico CNI"

step "Apply Calico"
if kubectl get ns calico-system &>/dev/null 2>&1 || \
   kubectl get daemonset calico-node -n kube-system &>/dev/null 2>&1; then
  skip "Calico already installed"
else
  run "Calico operator" kubectl create -f \
    https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/tigera-operator.yaml
  run "Calico CRs" kubectl create -f \
    https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/custom-resources.yaml
  _spin_start "Waiting for node Ready"
  for i in $(seq 1 40); do
    [[ "$(kubectl get nodes --no-headers 2>/dev/null | grep -c ' Ready' || echo 0)" -ge 1 ]] && break
    sleep 5
  done
  _spin_stop "Node Ready"
  _spin_start "Waiting for calico-node DaemonSet"
  kubectl rollout status daemonset/calico-node -n calico-system --timeout=120s >>"$LOG" 2>&1 || true
  _spin_stop "Calico network ready"
fi

# ══════════════════════════════════════════════════════════════════════════════
#  PHASE 4 — Ingress + TLS
# ══════════════════════════════════════════════════════════════════════════════
phase "Ingress + TLS"

step "Remove Traefik (conflicts with ingress-nginx on ports 80/443)"
_traefik_status=$(helm status traefik -n kube-system -o json 2>/dev/null | jq -r '.info.status' 2>/dev/null || echo "")
if [[ -n "$_traefik_status" ]]; then
  info "Traefik found (status=${_traefik_status}) — removing to free ports 80/443"
  helm uninstall traefik     -n kube-system >>"$LOG" 2>&1 || true
  helm uninstall traefik-crd -n kube-system >>"$LOG" 2>&1 || true
  mkdir -p /etc/rancher/k3s
  if ! grep -q 'disable.*traefik' /etc/rancher/k3s/config.yaml 2>/dev/null; then
    printf '\ndisable:\n  - traefik\n' >> /etc/rancher/k3s/config.yaml
  fi
  # Give k3s a moment to release the host ports before ingress-nginx tries to claim them
  sleep 5
  ok "Traefik removed; persisted disable in /etc/rancher/k3s/config.yaml"
else
  skip "Traefik not present"
fi

step "NGINX Ingress Controller"
_ing_status=$(helm status ingress-nginx -n ingress-nginx -o json 2>/dev/null | jq -r '.info.status' 2>/dev/null || echo "")
if [[ "$_ing_status" == "deployed" ]]; then
  skip "ingress-nginx"
else
  # Purge any leftover failed/pending release so helm install starts clean
  if [[ -n "$_ing_status" ]]; then
    info "Removing previous '${_ing_status}' ingress-nginx release"
    helm uninstall ingress-nginx -n ingress-nginx >>"$LOG" 2>&1 || true
  fi
  run "Install ingress-nginx chart" helm upgrade --install ingress-nginx ingress-nginx \
    --repo https://kubernetes.github.io/ingress-nginx \
    --namespace ingress-nginx --create-namespace \
    --set controller.hostNetwork=true --set controller.kind=DaemonSet \
    --set controller.admissionWebhooks.enabled=false
  _spin_start "Waiting for ingress-nginx DaemonSet (image pull may take a while)"
  kubectl rollout status daemonset/ingress-nginx-controller \
    -n ingress-nginx --timeout=15m >>"$LOG" 2>&1 \
    && _spin_stop "ingress-nginx ready" \
    || { _spin_stop "ingress-nginx (check: kubectl get pods -n ingress-nginx)"; warn "ingress-nginx not fully ready — continuing"; }
fi

step "cert-manager"
_cm_status=$(helm status cert-manager -n cert-manager -o json 2>/dev/null | jq -r '.info.status' 2>/dev/null || echo "")
if [[ "$_cm_status" == "deployed" ]]; then
  skip "cert-manager"
else
  [[ -n "$_cm_status" ]] && { info "Removing previous cert-manager release"; helm uninstall cert-manager -n cert-manager >>"$LOG" 2>&1 || true; }
  run "Install cert-manager chart" helm upgrade --install cert-manager cert-manager \
    --repo https://charts.jetstack.io \
    --namespace cert-manager --create-namespace \
    --set installCRDs=true
  _spin_start "Waiting for cert-manager"
  kubectl rollout status deployment/cert-manager -n cert-manager --timeout=10m >>"$LOG" 2>&1 \
    && _spin_stop "cert-manager ready" \
    || { _spin_stop "cert-manager (check: kubectl get pods -n cert-manager)"; warn "cert-manager not fully ready — continuing"; }
fi

# ══════════════════════════════════════════════════════════════════════════════
#  PHASE 5 — FDE application stack
# ══════════════════════════════════════════════════════════════════════════════
phase "FDE application stack"

step "Create namespace ${NS}"
maybe kubectl create namespace "${NS}" --dry-run=client -o yaml | kubectl apply -f - >>"$LOG" 2>&1
ok "Namespace ${NS} ready"

_helm_up() {
  local release="$1" chart="$2"; shift 2
  local status
  status=$(helm status "${release}" -n "${NS}" -o json 2>/dev/null | jq -r '.info.status' 2>/dev/null || echo "")
  if [[ "$status" == "deployed" ]]; then
    skip "${release}"
  else
    if [[ -n "$status" ]]; then
      info "Removing previous '${status}' release: ${release}"
      helm uninstall "${release}" -n "${NS}" >>"$LOG" 2>&1 || true
      sleep 5
    fi
    # Build subchart dependencies (loki-stack, kube-prometheus-stack, etc.) if needed
    if grep -q '^dependencies:' "${CHARTS_DIR}/${chart}/Chart.yaml" 2>/dev/null; then
      _spin_start "Building chart dependencies for ${chart}"
      helm dependency build "${CHARTS_DIR}/${chart}" >>"$LOG" 2>&1 \
        && _spin_stop "Dependencies ready" \
        || { _spin_stop "dep build"; warn "helm dependency build failed for ${chart} — continuing"; }
    fi
    run "Deploying ${release}" helm upgrade --install "${release}" "${CHARTS_DIR}/${chart}" \
      --namespace "${NS}" "$@"
    # Wait separately so a slow image pull warns instead of aborting the installer
    local _wl
    _wl=$(kubectl get deploy,sts -n "${NS}" \
      -l "app.kubernetes.io/instance=${release}" -o name 2>/dev/null | head -1 || true)
    if [[ -n "${_wl:-}" ]]; then
      _spin_start "Waiting for ${release}"
      kubectl rollout status "${_wl}" -n "${NS}" --timeout=15m >>"$LOG" 2>&1 \
        && _spin_stop "${release} ready" \
        || { _spin_stop "${release}"; warn "${release} not ready in 15m — check: kubectl get pods -n ${NS}"; }
    fi
  fi
}

$SVC_EMQX       && _helm_up "fde-emqx"      "emqx"       \
  --set "global.storageClass=local-path" \
  --set "auth.dashboard.password=${PW_EMQX}" \
  --set "nodePort.mqtt=31883" --set "nodePort.dashboard=32083"

$SVC_CLICKHOUSE && _helm_up "fde-clickhouse" "clickhouse" \
  --set "global.storageClass=local-path" --set "auth.username=default" \
  --set "auth.password=${PW_CLICKHOUSE}" --set "storage.data=20Gi" --set "storage.logs=2Gi" \
  --set "resources.requests.cpu=250m" --set "resources.requests.memory=512Mi" \
  --set "resources.limits.cpu=2000m" --set "resources.limits.memory=4Gi"

$SVC_NEO4J      && _helm_up "fde-neo4j"     "neo4j" \
  --set "global.storageClass=local-path" \
  --set "auth.password=${PW_NEO4J}" \
  --set "nodePort.bolt=32687" --set "nodePort.http=32474"

$SVC_QDRANT     && _helm_up "fde-qdrant"    "qdrant"     \
  --set "global.storageClass=local-path" --set "storage.data=5Gi" \
  --set "resources.requests.cpu=100m" --set "resources.requests.memory=256Mi" \
  --set "resources.limits.cpu=1000m" --set "resources.limits.memory=2Gi"

$SVC_PGADMIN    && _helm_up "fde-pgadmin"   "pgadmin"    \
  --set "global.storageClass=local-path" --set "auth.email=admin@fde.local" \
  --set "auth.password=${PW_PGADMIN}"

$SVC_MAESTROHUB && _helm_up "fde-maestrohub" "maestrohub" \
  --set "global.storageClass=local-path"

$SVC_IGNITION   && _helm_up "fde-ignition"  "ignition"   \
  --set "global.storageClass=local-path" --set "auth.username=admin" \
  --set "auth.password=${PW_IGNITION}" \
  --set "service.httpNodePort=30088" --set "service.httpsNodePort=30669"

$SVC_LITMUSEDGE && _helm_up "fde-litmusedge" "litmusedge" \
  --set "global.storageClass=local-path"

$SVC_LOKI       && _helm_up "fde-loki"      "loki"       \
  --set "global.storageClass=local-path" \
  --set "loki-stack.loki.persistence.size=10Gi" \
  --set "loki-stack.loki.persistence.storageClassName=local-path"

$SVC_MONITORING && _helm_up "fde-monitoring" "monitoring" \
  --set "kube-prometheus-stack.grafana.adminPassword=${PW_GRAFANA}" \
  --set "kube-prometheus-stack.grafana.persistence.storageClassName=local-path" \
  --set "kube-prometheus-stack.grafana.persistence.size=1Gi" \
  --set "kube-prometheus-stack.prometheus.prometheusSpec.retention=7d" \
  --set "kube-prometheus-stack.prometheus.prometheusSpec.retentionSize=5GB" \
  --set "kube-prometheus-stack.prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.storageClassName=local-path" \
  --set "kube-prometheus-stack.prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.resources.requests.storage=8Gi" \
  --set "kube-prometheus-stack.alertmanager.alertmanagerSpec.storage.volumeClaimTemplate.spec.storageClassName=local-path" \
  --set "kube-prometheus-stack.alertmanager.alertmanagerSpec.storage.volumeClaimTemplate.spec.resources.requests.storage=512Mi"

if $SVC_PREDMAINT; then
  step "Helm: predmaint"
  _ps=$(helm status predmaint -n "${NS}" -o json 2>/dev/null | jq -r '.info.status' 2>/dev/null || echo "")
  if [[ "$_ps" == "deployed" ]]; then
    skip "predmaint"
  else
    _pm_args=()
    [[ -n "$VLLM_URL" ]] && _pm_args+=(--set "llm.endpoint=${VLLM_URL}")
    run "Deploying predmaint" helm upgrade --install predmaint "${CHARTS_DIR}/predmaint" \
      --namespace "${NS}" --wait --timeout 10m \
      --set "env.CLICKHOUSE_URL=http://fde-clickhouse-clickhouse.uns.svc.cluster.local:8123" \
      --set "env.CLICKHOUSE_USER=default" \
      --set "env.CLICKHOUSE_PASSWORD=${PW_CLICKHOUSE}" \
      --set "env.MQTT_BROKER=fde-emqx-svc.uns.svc.cluster.local" \
      --set "env.MQTT_PORT=1883" \
      --set "env.MQTT_ALARM_ENABLED=true" \
      --set "env.UNS_GROUP=dc" \
      --set "env.UNS_EDGE_NODE=blans" \
      --set "env.SCAN_INTERVAL_S=300" \
      "${_pm_args[@]}"
  fi
fi

# ══════════════════════════════════════════════════════════════════════════════
#  PHASE 6 — K8s resources (NodePorts + Ingress)
# ══════════════════════════════════════════════════════════════════════════════
phase "K8s resources"

step "NodePort external services"
maybe kubectl apply -n "${NS}" -f - >>"$LOG" 2>&1 <<'YAML'
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata: {name: fde-emqx-ext}
  spec:
    type: NodePort
    selector: {app: fde-emqx}
    ports:
    - {name: mqtt,      port: 1883,  targetPort: 1883,  nodePort: 31883}
    - {name: dashboard, port: 18083, targetPort: 18083, nodePort: 32083}
- apiVersion: v1
  kind: Service
  metadata: {name: fde-clickhouse-ext}
  spec:
    type: NodePort
    selector: {app.kubernetes.io/instance: fde-clickhouse, app.kubernetes.io/name: clickhouse}
    ports: [{port: 8123, targetPort: 8123, nodePort: 32123}]
- apiVersion: v1
  kind: Service
  metadata: {name: fde-qdrant-ext}
  spec:
    type: NodePort
    selector: {app.kubernetes.io/instance: fde-qdrant, app.kubernetes.io/name: qdrant}
    ports: [{port: 6333, targetPort: 6333, nodePort: 32333}]
- apiVersion: v1
  kind: Service
  metadata: {name: fde-predmaint-ext}
  spec:
    type: NodePort
    selector: {app.kubernetes.io/instance: predmaint, app.kubernetes.io/name: predmaint}
    ports:
    - {name: mcp, port: 5100, targetPort: 5100, nodePort: 32100}
    - {name: metrics, port: 9090, targetPort: 9090, nodePort: 32091}
- apiVersion: v1
  kind: Service
  metadata: {name: fde-prometheus-ext}
  spec:
    type: NodePort
    selector:
      app.kubernetes.io/name: prometheus
      operator.prometheus.io/name: fde-monitoring-kube-promet-prometheus
    ports: [{port: 9090, targetPort: 9090, nodePort: 32090}]
YAML
ok "NodePort services applied"

step "Ingress rules"
maybe kubectl apply -n "${NS}" -f - >>"$LOG" 2>&1 <<YAML
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fde-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: grafana.${DOMAIN}
    http:
      paths: [{path: /, pathType: Prefix, backend: {service: {name: fde-monitoring-grafana, port: {number: 80}}}}]
  - host: ignition.${DOMAIN}
    http:
      paths: [{path: /, pathType: Prefix, backend: {service: {name: fde-ignition-ignition, port: {number: 8088}}}}]
  - host: clickhouse.${DOMAIN}
    http:
      paths: [{path: /, pathType: Prefix, backend: {service: {name: fde-clickhouse-clickhouse, port: {number: 8123}}}}]
  - host: qdrant.${DOMAIN}
    http:
      paths: [{path: /, pathType: Prefix, backend: {service: {name: fde-qdrant-qdrant, port: {number: 6333}}}}]
  - host: maestro.${DOMAIN}
    http:
      paths: [{path: /, pathType: Prefix, backend: {service: {name: fde-maestrohub-maestrohub, port: {number: 5678}}}}]
  - host: pgadmin.${DOMAIN}
    http:
      paths: [{path: /, pathType: Prefix, backend: {service: {name: fde-pgadmin-pgadmin, port: {number: 80}}}}]
  - host: alerts.${DOMAIN}
    http:
      paths: [{path: /, pathType: Prefix, backend: {service: {name: fde-monitoring-kube-promet-alertmanager, port: {number: 9093}}}}]
YAML
ok "Ingress rules applied"

# ══════════════════════════════════════════════════════════════════════════════
#  PHASE 7 — MCP servers
# ══════════════════════════════════════════════════════════════════════════════
phase "MCP servers"

if [[ -f "$MCP_YAML" ]]; then
  step "Apply mcp-servers-deployment.yaml"
  run "Applying MCP deployment" kubectl apply -f "$MCP_YAML" -n "${NS}"
else
  warn "mcp-servers-deployment.yaml not found at ${MCP_YAML} — skipping MCP deployment"
fi

# ══════════════════════════════════════════════════════════════════════════════
#  PHASE 8 — Obsidian viewer (optional)
# ══════════════════════════════════════════════════════════════════════════════
if $SVC_OBSIDIAN && [[ -n "$OBS_URL" ]]; then
  phase "Obsidian vault viewer"
  step "Deploy obsidian-viewer"
  maybe kubectl apply -n "${NS}" -f - >>"$LOG" 2>&1 <<YAML
apiVersion: v1
kind: ConfigMap
metadata:
  name: obsidian-viewer-config
data:
  OBS_URL: "${OBS_URL}"
  OBS_KEY: "${OBS_KEY}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: obsidian-viewer
spec:
  replicas: 1
  selector:
    matchLabels: {app: obsidian-viewer}
  template:
    metadata:
      labels: {app: obsidian-viewer}
    spec:
      containers:
      - name: viewer
        image: python:3.12-slim
        command: ["/bin/sh","-c","pip install -q flask requests markdown && python3 -m flask --app viewer run --host 0.0.0.0 --port 5000"]
        envFrom: [{configMapRef: {name: obsidian-viewer-config}}]
        ports: [{containerPort: 5000}]
        readinessProbe:
          httpGet: {path: /health, port: 5000}
          initialDelaySeconds: 30
        resources:
          requests: {cpu: 50m, memory: 128Mi}
          limits: {cpu: 200m, memory: 256Mi}
---
apiVersion: v1
kind: Service
metadata:
  name: obsidian-viewer
spec:
  type: NodePort
  selector: {app: obsidian-viewer}
  ports: [{port: 80, targetPort: 5000, nodePort: 32400}]
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fde-obsidian-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: notes.${DOMAIN}
    http:
      paths: [{path: /, pathType: Prefix, backend: {service: {name: obsidian-viewer, port: {number: 80}}}}]
YAML
  ok "Obsidian viewer deployed → http://notes.${DOMAIN}"
fi

# ══════════════════════════════════════════════════════════════════════════════
#  PHASE 9 — Ignition modules
# ══════════════════════════════════════════════════════════════════════════════
if $SVC_IGNITION && [[ -d "${IGN_MODULES_DIR}" ]]; then
  phase "Ignition modules"
  step "Copy .modl files"
  _spin_start "Waiting for Ignition pod"
  for i in $(seq 1 30); do
    kubectl get pod -n "${NS}" -l app.kubernetes.io/name=ignition \
      --field-selector=status.phase=Running --no-headers 2>/dev/null | grep -q "Running" && break
    sleep 5
  done
  _spin_stop "Ignition pod ready"
  IGN_POD=$(kubectl get pod -n "${NS}" -l app.kubernetes.io/name=ignition \
    -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || true)
  if [[ -n "${IGN_POD:-}" ]]; then
    for modl in "${IGN_MODULES_DIR}"/*.modl; do
      [[ -f "${modl}" ]] || continue
      run "Installing $(basename "${modl}")" kubectl cp \
        "${modl}" "${NS}/${IGN_POD}:/usr/local/bin/ignition/user-lib/modules/$(basename "${modl}")"
    done
    ok "Modules installed (Ignition will pick them up on restart)"
  else
    warn "Ignition pod not found — copy modules manually"
  fi
fi

# ══════════════════════════════════════════════════════════════════════════════
#  PHASE 10 — Verification
# ══════════════════════════════════════════════════════════════════════════════
phase "Verification"

step "Pod status (ns=${NS})"
printf "\n"
kubectl get pods -n "${NS}" --no-headers 2>/dev/null | \
  awk '{
    name=$1; ready=$2; status=$4
    if (status=="Running")    printf "      \033[38;5;82m✔\033[0m  %-52s %s  (%s)\n", name, status, ready
    else if (status~/^Compl/) printf "      \033[38;5;82m✔\033[0m  %-52s %s\n",       name, status
    else                      printf "      \033[38;5;220m⚠\033[0m  %-52s %s\n",       name, status
  }' || true
printf "\n"

step "Helm releases"
printf "\n"
helm list -A --no-headers 2>/dev/null | \
  awk '{
    name=$1; ns=$2; status=$6
    if (status=="deployed") printf "      \033[38;5;82m✔\033[0m  %-28s ns=%-14s %s\n", name, ns, status
    else                    printf "      \033[38;5;220m⚠\033[0m  %-28s ns=%-14s %s\n", name, ns, status
  }' || true
printf "\n"

# ── Persist configuration to .env ────────────────────────────────────────────
step "Writing configuration to .env"
cat > "${FDE_ENV_FILE}" <<ENVEOF
# FDE Platform configuration — written by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Sourced automatically on next install.sh run (provides defaults for all prompts).
# DO NOT commit this file — it contains credentials. It is in .gitignore.

FDE_NODE_IP="${NODE_IP}"
FDE_DOMAIN="${DOMAIN}"
FDE_NS="${NS}"

FDE_PW_CLICKHOUSE="${PW_CLICKHOUSE}"
FDE_PW_EMQX="${PW_EMQX}"
FDE_PW_NEO4J="${PW_NEO4J}"
FDE_PW_IGNITION="${PW_IGNITION}"
FDE_PW_GRAFANA="${PW_GRAFANA}"
FDE_PW_PGADMIN="${PW_PGADMIN}"

FDE_VLLM_URL="${VLLM_URL:-}"
ENVEOF
chmod 600 "${FDE_ENV_FILE}"
ok ".env written  →  ${FDE_ENV_FILE}"

# ══════════════════════════════════════════════════════════════════════════════
#  POST-INSTALL SUMMARY
# ══════════════════════════════════════════════════════════════════════════════
_hr() { printf "  ${D}%s${N}\n" "────────────────────────────────────────────────────────────"; }

printf "\n"
printf "${P}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}\n"
printf "${W} FDE Platform deployed!  Node: %s${N}\n" "$NODE_IP"
printf "${P}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}\n\n"

printf "  ${W}Service endpoints${N}\n"; _hr
$SVC_IGNITION   && printf "  ${P}%-22s${N}  http://ignition.%s  (%s / %s)\n"      "Ignition SCADA"    "$DOMAIN" "admin"           "$PW_IGNITION"
$SVC_MONITORING && printf "  ${P}%-22s${N}  http://grafana.%s   (%s / %s)\n"      "Grafana"           "$DOMAIN" "admin"           "$PW_GRAFANA"
$SVC_PGADMIN    && printf "  ${P}%-22s${N}  http://pgadmin.%s   (%s / %s)\n"      "pgAdmin"           "$DOMAIN" "admin@fde.local"  "$PW_PGADMIN"
$SVC_MAESTROHUB && printf "  ${P}%-22s${N}  http://maestro.%s\n"                  "MaestroHub (n8n)"  "$DOMAIN"
$SVC_MONITORING && printf "  ${P}%-22s${N}  http://alerts.%s\n"                   "AlertManager"      "$DOMAIN"
$SVC_OBSIDIAN   && printf "  ${P}%-22s${N}  http://notes.%s\n"                    "Obsidian viewer"   "$DOMAIN"
$SVC_EMQX       && printf "  ${P}%-22s${N}  mqtt://%s:31883 / http://%s:32083\n"  "EMQX MQTT/UI"      "$NODE_IP" "$NODE_IP"
$SVC_PREDMAINT  && printf "  ${P}%-22s${N}  http://%s:32100/mcp\n"              "predmaint MCP"     "$NODE_IP"
$SVC_CLICKHOUSE && printf "  ${P}%-22s${N}  http://%s:32123\n"                    "ClickHouse HTTP"   "$NODE_IP"
$SVC_QDRANT     && printf "  ${P}%-22s${N}  http://%s:32333\n"                    "Qdrant REST"       "$NODE_IP"
$SVC_NEO4J      && printf "  ${P}%-22s${N}  bolt://%s:32687\n"                    "Neo4j"             "$NODE_IP"
$SVC_MONITORING && printf "  ${P}%-22s${N}  http://%s:32090\n"                    "Prometheus"        "$NODE_IP"
$SVC_IGNITION   && printf "  ${P}%-22s${N}  http://%s:30088\n"                    "Ignition NodePort" "$NODE_IP"

printf "\n  ${W}/etc/hosts${N} — add to client machines:\n"; _hr
printf "  ${G}%s  %s grafana.%s ignition.%s${N}\n" \
  "$NODE_IP" "$DOMAIN" "$DOMAIN" "$DOMAIN"
printf "  ${G}%s  clickhouse.%s qdrant.%s maestro.%s pgadmin.%s alerts.%s${N}\n" \
  "$NODE_IP" "$DOMAIN" "$DOMAIN" "$DOMAIN" "$DOMAIN" "$DOMAIN"
$SVC_OBSIDIAN && printf "  ${G}%s  notes.%s${N}\n" "$NODE_IP" "$DOMAIN"

if [[ "$DEPLOY_MODE" == "control-plane" ]]; then
  printf "\n  ${W}Worker join${N}\n"; _hr
  _tok=$(cat /var/lib/rancher/k3s/server/node-token 2>/dev/null || echo "N/A")
  printf "  Token: ${Y}%s${N}\n" "$_tok"
  printf "  sudo ./install.sh --mode worker \\\\\n"
  printf "    --join-url https://%s:6443 \\\\\n" "$NODE_IP"
  printf "    --join-token <token> \\\\\n"
  printf "    --worker-tier worker|stateful|ot-edge\n"
fi

printf "\n  ${D}Log: %s${N}\n" "$LOG"
printf "  ${D}Quick check: kubectl get pods -n uns && helm list -A${N}\n\n"
