apiVersion: v1
kind: Service
metadata:
  name: {{ include "timebase.fullname" . }}-explorer
  namespace: {{ .Release.Namespace }}
  labels: {{- include "timebase.labels" . | nindent 4 }}
spec:
  selector: {{- include "timebase.explorer.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.explorer.port }}
      targetPort: {{ .Values.service.explorer.port }}
      name: http
