apiVersion: v1
kind: Secret
metadata:
  name: {{ include "maestrohub.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels: {{- include "maestrohub.labels" . | nindent 4 }}
type: Opaque
stringData:
  N8N_BASIC_AUTH_USER: {{ .Values.auth.username | quote }}
  N8N_BASIC_AUTH_PASSWORD: {{ .Values.auth.password | quote }}
