apiVersion: v1
kind: Service
metadata:
  name: {{ include "maestrohub.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "maestrohub.labels" . | nindent 4 }}
spec:
  selector: {{- include "maestrohub.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: http
