apiVersion: v1
kind: Secret
metadata:
  name: {{ include "emqx.fullname" . }}-secret
  labels:
    {{- include "emqx.labels" . | nindent 4 }}
type: Opaque
stringData:
  EMQX_DASHBOARD_PASSWORD: {{ .Values.auth.dashboard.password | quote }}
