apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clickhouse.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels: {{- include "clickhouse.labels" . | nindent 4 }}
data:
  override.xml: |
    <clickhouse>
      <timezone>Europe/Budapest</timezone>
      <logger>
        <level>warning</level>
      </logger>
    </clickhouse>
  users-override.xml: |
    <clickhouse>
      <profiles>
        <default>
          <max_memory_usage>4000000000</max_memory_usage>
        </default>
      </profiles>
    </clickhouse>
  init.sql: |
    CREATE DATABASE IF NOT EXISTS uns;
    CREATE TABLE IF NOT EXISTS uns.sensor_raw
    (
        ts        DateTime64(3, 'UTC'),
        topic     LowCardinality(String),
        cell      LowCardinality(String),
        tag       LowCardinality(String),
        value_num Nullable(Float64),
        value_str Nullable(String)
    )
    ENGINE = MergeTree()
    PARTITION BY toYYYYMMDD(ts)
    ORDER BY (cell, tag, ts)
    TTL ts + INTERVAL 2 YEAR
    SETTINGS index_granularity = 8192;
