apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pgadmin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "pgadmin.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "pgadmin.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels: {{- include "pgadmin.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: pgadmin
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "pgadmin.fullname" . }}-auth
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          readinessProbe:
            httpGet:
              path: /misc/ping
              port: {{ .Values.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 6
          resources: {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/pgadmin
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "pgadmin.fullname" . }}-data
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations: {{- toYaml .Values.tolerations | nindent 8 }}
      affinity: {{- toYaml .Values.affinity | nindent 8 }}
