apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgadmin.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels: {{- include "pgadmin.labels" . | nindent 4 }}
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: {{ .Values.auth.email | quote }}
  PGADMIN_DEFAULT_PASSWORD: {{ .Values.auth.password | quote }}
