{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "predmaint.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "predmaint.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "predmaint.fullname" . }}
                port:
                  name: mcp
{{- end }}
