apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neo4j.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels: {{- include "neo4j.labels" . | nindent 4 }}
type: Opaque
stringData:
  NEO4J_AUTH: "{{ .Values.auth.username }}/{{ .Values.auth.password }}"
