apiVersion: v1
kind: Secret
metadata:
  name: {{ include "litmusedge.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels: {{- include "litmusedge.labels" . | nindent 4 }}
type: Opaque
stringData:
  LITMUSEDGE_ADMIN_USERNAME: {{ .Values.auth.adminUsername | quote }}
  LITMUSEDGE_ADMIN_PASSWORD: {{ .Values.auth.adminPassword | quote }}
