replicaCount: 1

image:
  repository: neo4j
  tag: "5.26.28-community"
  pullPolicy: IfNotPresent

auth:
  username: neo4j
  password: "CHANGEME"

resources:
  requests:
    cpu: "500m"
    memory: "1.5Gi"
  limits:
    cpu: "2000m"
    memory: "2Gi"

storage:
  data: 5Gi

nodePort:
  bolt: 32687
  http: 32474

config:
  heap_initial_size: 512m
  heap_max_size: 1G
  pagecache_size: 512m

global:
  storageClass: ""

nodeSelector: {}
tolerations: []
affinity: {}
